name: Use github actions to build and deploy.

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Change directory
      run: cd angular-demo

    - name: Build and deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.action_token }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: yarn install && yarn run build
        
